# ag
# don't ignore files in .gitignore
alias ag='ag -U'

# git status
alias s='git status'
alias d='git diff'

# temporarily
alias nvim='maltimore_you_should_learn_to_use_vim_instead_of_nvim_as_a_command'

# start uncommited_changes_sync in the background and redirect its output
alias uncommitted-changes-sync='(cd "$HOME"/repos/uncommitted-changes-sync; ./sync config > /tmp/uncommitted-changes-sync_log 2>&1) &'

# start jupyterlab hidden
alias jplab_hidden='jupyter lab > /tmp/jplab_hidden_output 2>&1 &'

# tensorboard port forwarding
# -N for no remote commands
# -f to put ssh into the background (I don't use this for now)
# -L for port forwarding
alias tbportforward='ssh -N -L 16006:localhost:6006 ida > /tmp/tbportforward_output 2>&1 &'
